services:
  web:
    image: case2classification:1.0
    environment:
      - gpus=all
    network_mode: "host"
    volumes:
      - /mnt/data/wwm_large_ext:/workspace/wwm_large_ext
      - /mnt/data/ayfl2/model/bert:/workspace/model/bert/
      - /mnt/data/ayfl2/log:/workspace/data
    command: python3 torch_server.py -p 58082
