services:
  web:
    image: caseargue:1.1
    environment:
      - gpus=all
    network_mode: "host"
    container_name: caseargue_large
    volumes:
      - /mnt/data/lbwj/data:/workspace/data
      - /mnt/data/wwm_large_ext:/workspace/roberta_wwm_large_ext
      - /mnt/data/lbwj/model/lbert:/workspace/model/bert/
    command: python3 torch_server.py -c config/bert_config_large.json -p 58093
