services:
  web:
    image: caseargue:1.1
    environment:
      - gpus=all
    network_mode: "host"
    container_name: caseargue_light
    volumes:
      - /mnt/data/lbwjdocker/log:/workspace/data
      - /mnt/data/roberta3_large_ext:/workspace/roberta3_large_ext
      - /mnt/data/lbwjdocker/model/bert:/workspace/model/bert/
    command: python3 torch_server.py -p 58091
