services:
  web:
    image: contractamount:2.0
    network_mode: "host"
    environment:
    - PYTHONIOENCODING=utf8
    volumes:
    - /mnt/data/jesbdocker/log:/workspace/data
    - /mnt/data/jesb2/model_data_v6:/workspace/model_data_v6
    - /mnt/data/jesbdocker/model:/workspace/model
    container_name: contractamount_with_type
    command: python3 tensorflow_server_v2.py -m model_data_v6 -c config/lstm_config.json -p 58099
