services:
  web:
    image: contractamount:1.0
    network_mode: "host"
    volumes:
    - /mnt/data/jesbdocker/log:/workspace/data
    - /mnt/data/jesbdocker/model_data_v6:/workspace/model_data_v6
    command: python3 tensorflow_server.py -m model_data_v6 -p 58090
