services:
  web:
    image: xlnetwordsegment:1.0
    environment:
      - gpus=all
    network_mode: "host"
    container_name: xlnet_word_segment
    volumes:
    - /mnt/data/zwfcdocker/model:/workspace/model
    - /mnt/data/zwfcdocker/log:/workspace/data
    - /mnt/data/xlnet_base:/workspace/xlnet_base
    command: python3 torch_server.py -p 58076 -c config/bert_config-xl.json